[package]
name = "crypti"
version = "0.2.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
iced-x86 = "1.21.0"
goblin = "0.10"
clap = { version = "4.5.41", features = ["derive"] }
clap-num = "1.2.0"
bytemuck = "1.23.1"

[profile.release]
lto = true
